# Generated by Django 4.2.1 on 2023-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=100, unique=True)),
                ('long', models.CharField(max_length=256)),
            ],
        ),
    ]
